name: Build 3D Contribution Calendar

on:
  schedule:
    - cron: "0 18 * * *"     # runs daily at 18:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate 3D Calendar
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push SVG
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add profile-3d-contrib/
          git commit -m "Update 3D calendar" || echo "No changes"
          git push
